modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/Flanks255/simplylight/issues"
[[mods]]
modId="simplylight"
version="${file.jarVersion}"
displayName="Simply Light"
logoFile="logo.png"
credits=""
authors="Flanks255"
description='''Simple light, for a complicated world.'''
[[dependencies.simplylight]]
modId="forge"
mandatory=true
versionRange="[45.1.0,)"
ordering="NONE"
side="BOTH"