plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    def commonResources = project(':common').file('src/main/resources/')
    def ENV = System.getenv()
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            programArguments.addAll('--width', '1280', '--height', '720')
            if (ENV.MCDEVUSER) {
                programArguments.addAll('--username', ENV.MCDEVUSER)
            }
            if (ENV.MCDEVUUID) {
                programArguments.addAll('--uuid', ENV.MCDEVUUID)
            }
        }
        data {
            data()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', 'simplylight', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath(), '--existing', commonResources.getAbsolutePath()

        }
        server {
            server()
            programArguments.addAll('--nogui')
        }
    }
    mods {
        "simplylight" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = 'https://maven.creeperhost.net/' }
    maven { url = 'https://www.cursemaven.com' }
    maven { url = 'https://maven.saps.dev/releases' }
}

dependencies {
    compileOnly "mezz.jei:jei-${jei_mc_version}-common-api:${jei_version}"//new
    compileOnly "mezz.jei:jei-${jei_mc_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${jei_mc_version}-neoforge:${jei_version}"

//    compileOnly fg.deobf("curse.maven:TOP-245211:4159743")
    runtimeOnly "curse.maven:JADE-324717:6853386"
    runtimeOnly "curse.maven:ATLAS-633577:5490697"
    runtimeOnly "curse.maven:CTM-267602:5587515"
    runtimeOnly "curse.maven:BUILDINGGADGETS-298187:5968587"
}